spring.application.name=server
server.port=8081
spring.config.import=optional:file:./server/.env[.properties],optional:file:./.env[.properties]
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://hettiarachchianuk01_db_user:TgG3mAMs7MVupy8N@cluster0.uc9vjll.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0}
spring.data.mongodb.database=${MONGODB_DATABASE:paf_auth}
spring.data.mongodb.auto-index-creation=false
auth.google.client-id=${GOOGLE_CLIENT_ID:}
auth.linkedin.client-id=${LINKEDIN_CLIENT_ID:}
auth.linkedin.client-secret=${LINKEDIN_CLIENT_SECRET:}
auth.linkedin.redirect-uri=${LINKEDIN_REDIRECT_URI:}
auth.linkedin.client-redirect-uri=${LINKEDIN_CLIENT_REDIRECT_URI:http://localhost:5173/}
auth.github.client-id=${GITHUB_CLIENT_ID:}
auth.github.client-secret=${GITHUB_CLIENT_SECRET:}
auth.github.redirect-uri=${GITHUB_REDIRECT_URI:}
auth.github.client-redirect-uri=${GITHUB_CLIENT_REDIRECT_URI:http://localhost:5173/}
server.servlet.session.timeout=30m
server.servlet.session.cookie.name=PAFSESSIONID
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax
server.tomcat.max-http-form-post-size=10MB
server.tomcat.max-swallow-size=10MB
