spring.application.name=server
server.port=8080
spring.config.import=optional:file:./server/.env[.properties],optional:file:./.env[.properties]
spring.datasource.url=${DB_URL:jdbc:h2:mem:pafdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.h2.console.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=15MB
ticket.storage.location=${TICKET_STORAGE_LOCATION:uploads/tickets}
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://hettiarachchianuk01_db_user:TgG3mAMs7MVupy8N@cluster0.uc9vjll.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0}
spring.data.mongodb.database=${MONGODB_DATABASE:paf_auth}
spring.data.mongodb.auto-index-creation=false
auth.google.client-id=${GOOGLE_CLIENT_ID:}
server.servlet.session.timeout=30m
server.servlet.session.cookie.name=PAFSESSIONID
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax
